### PR TITLE
Update repository to apt.tvheadend.org

### LINKED ISSUE #21: The repository for tvheadend has changed
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5
- Ruby: N/A
- Distribution: Ubuntu bionic
- Module version: 0.1.1

## How to reproduce (e.g Puppet code you use)
The repository for tvheadend has changed (see https://tvheadend.org/projects/tvheadend/wiki/AptRepositories)

## What are you seeing
tvheadend package is not found 

## What behaviour did you expect instead
Successful install of tvheadend

## Output log
n/a

## Any additional information you'd like to impart
n/a

### PR DESCRIPTION
**Pull request by mergwyn**
#### Pull Request (PR) description
Updates repository as per https://tvheadend.org/projects/tvheadend/wiki/AptRepositories

#### This Pull Request (PR) fixes the following issues

Fixes #21

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @mergwyn, thanks for the PR. Can you please squash the comits down?

**Comment by mergwyn** [comment]
I can do - but how do I do that?

Gary

**Comment by bastelfreak** [comment]
Hi. A brief overview:
* clone your repo
* Add our repo as another remote and do a `git fetch --all --prune`
* do an interactive rebase against our master with `git rebase -i $voxpupuliremote/master`
* Select all but the first commit for fixup
* Do a `git push -f`

You can join our IRC channel #voxpupuli on freenode or our slack channel at https://slack.puppet.com if you've more questions or run into specific issues. Those are easier to handle during a real chat.

**Comment by mergwyn** [comment]
Squash done (I think), now error "Gem::RuntimeRequirementNotMetError: parallel_tests requires Ruby version >= 2.2.0. The current ruby version is 2.1.0."  Not sure what this is!

**Comment by bastelfreak** [comment]
@mergwyn, sorry for not coming back to you, this PR slipt through. Would you mind rebasing against our latest master?

**Comment by mergwyn** [comment]
Hopefully this is OK now.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
